<a href="https://colab.research.google.com/github/7ayush/FourSem/blob/main/ML_Assignment-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Yash Aggarwal 10190276 3COE11 Numpy

In [1]:
import numpy as np
arr = np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [2]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [3]:
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [4]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
arr = np.random.normal(0,1,25)
arr

array([ 2.12132181,  0.76386233,  0.99666359,  0.14296766, -0.95380716,
       -1.03695927,  0.32730246, -0.07519346, -0.27835399, -0.57792838,
       -0.99117061,  0.58900378,  2.765291  , -0.18791491,  1.70075908,
       -1.12368549, -0.41283881, -0.41727516,  0.07880307,  1.23958272,
        1.42703979,  0.0569652 , -0.70899477, -0.7389405 , -0.16780649])

In [6]:
arr = np.arange(0,1.01,0.01)
arr

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [7]:
arr = np.around(np.linspace(0,1,20),decimals=2)
arr

array([0.  , 0.05, 0.11, 0.16, 0.21, 0.26, 0.32, 0.37, 0.42, 0.47, 0.53,
       0.58, 0.63, 0.68, 0.74, 0.79, 0.84, 0.89, 0.95, 1.  ])

In [8]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
arr1 = arr[2:,:]
arr1

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
arr2 = arr[0:3,1:2]
arr2

array([[ 2],
       [ 7],
       [12]])

In [11]:
sum = np.sum(arr)
sum

325

In [12]:
rsum = np.sum(arr,axis=1)
rsum

array([ 15,  40,  65,  90, 115])

In [13]:
rcol = np.sum(arr,axis=0)
rcol

array([55, 60, 65, 70, 75])